### ISSUE TITLE
Does the app still track location when moving to background?

### ISSUE THREAD

**Issue by bradleybarbier** [shernandezp/XamarinForms.LocationService#10]
Hi, thanks for the great sample!

I ran the app to test if you still get updates when the app moves to the background on Android.
I put breakpoints to test, and it seems it does not update in the background.

I noticed the service is started as a foreground service, so it should theoretically work.
Is this a known limitation, or can something be modified to enable background updates?

Thanks again!

**Comment by shernandezp** [comment]
Hi @bradleybarbier , You can refer to the other thread in which people explain their results and findings on this issue.
