### ISSUE TITLE
Android Runtime Exception

### ISSUE THREAD

**Issue by johng1492** [shernandezp/XamarinForms.LocationService#12]
**Describe the bug**
When trying to start location service, in foreground, on Android, I get the error: Bad notification posted from package com.xxx.xxxxxxx: Couldn't create icon: StatusBarIcon(. 

The issue is on starting the service and I have tried for hours on what the issue is. I think it's a NULL that I'm passing someplace that is expecting a value.

**To Reproduce**
1. Call: MessagingCenter.Send(message, "ServiceStarted"); from FORMS
2. Here is the method (same as your sample):
MessagingCenter.Subscribe<StartServiceMessage>(this, "ServiceStarted", message => {
                if (!IsServiceRunning(typeof(AndroidLocationService)))
                {
                    if (Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
                    {
                        StartForegroundService(serviceIntent);
                    }
                    else
                    {
                        StartService(serviceIntent);
                    }
                }
            });

3. Here is the LocationService StartCommand: public override StartCommandResult OnStartCommand(Intent intent, StartCommandFlags flags, int startId)
		{
			_cts = new CancellationTokenSource();

			Notification notif = DependencyService.Get<INotification>().ReturnNotif();
			StartForeground(SERVICE_RUNNING_NOTIFICATION_ID, notif);

			Task.Run(() => {
				try
				{
					var locShared = new Location();
					locShared.Run(_cts.Token).Wait();
				}
				catch (OperationCanceledException)
				{
				}
				finally
				{
					if (_cts.IsCancellationRequested)
					{
						var message = new StopServiceMessage();
						Device.BeginInvokeOnMainThread(
							() => MessagingCenter.Send(message, "ServiceStopped")
						);
					}
				}
			}, _cts.Token);

			return StartCommandResult.Sticky;
		}

4. It seems like it bombs on: locShared.Run(_cts.Token).Wait(); above.

**Expected behavior**
To start the location service and track the user's location

**Smartphone (please complete the following information):**
 - Device: Old Samsung Device
 - OS: Android

**Comment by shernandezp** [comment]
I understand you are getting an error based on a change you made to the original code, the current code does not throw any kind of error. I suggest you go throw the documentation of Messaging Center:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center
