### ISSUE TITLE
Issue When Using Inside Shell Tabbed Page

### ISSUE THREAD

**Issue by nialmcshane** [shernandezp/XamarinForms.LocationService#13]
Hi,

I have implemented the code and all works fine but I am having an issue when using in a shell app with a tabbed page. When debugging it throws an unhandled exception error Java.Lang.IllegalStateException: 'FragmentManager is already executing transactions'.

Would it be possible for you to help me out or have you come across similar issues?

Thanks,

**Comment by shernandezp** [comment]
I'm afraid you have to troubleshoot and find the issue by yourself, I have tons of work these days.
