### ISSUE TITLE
Sharing the location with Server

### ISSUE THREAD

**Issue by walnut-co** [shernandezp/XamarinForms.LocationService#4]
Hi , are you help with sharing the location with server. Whenever, there is a movement or new location is available, send the information to server, regardless of being in foreground or background.

how would you handle the background communication restriction in iOS ?

Thanks

**Comment by shernandezp** [comment]
Hello.
Sharing location to server-side is not a feature of the current application, so, I'm closing this issue. Even so, there are multiple ways to do it, that is something you may need to investigate by yourself.
