### ISSUE TITLE
My Android OS 10 sample code of this working properly with 2 seconds refresh, but mobile phone lock and idle mode  with screen off GPS track only 6 or 8 time in a Minute. Please help to fix this.

### ISSUE THREAD

**Issue by JanakaND** [shernandezp/XamarinForms.LocationService#6]
My Android OS 10 sample code of this working properly with 2 seconds refresh, but mobile phone lock and idle mode  with screen off GPS track only 6 or 8 time in a Minute. Please help to fix this.

**Comment by shernandezp** [comment]
I invite you to understand the source code, test it, and to read the other threads before asking questions. You will see that @ormesam points to a workaround for some devices that block the background service in Android.

**Comment by ormesam** [comment]
On Android, if you want to receive location updates while the app is minimised and/or screen locked you need a foreground service (with the type set to Location or some phones will kill the it).
