### ISSUE TITLE
Could you explain this code from MainActivity.cs

### ISSUE THREAD

**Issue by Davester34** [shernandezp/XamarinForms.LocationService#8]
serviceIntent = new Intent(this, typeof(AndroidLocationService));
            SetServiceMethods();

            if (Build.VERSION.SdkInt >= BuildVersionCodes.M && !Android.Provider.Settings.CanDrawOverlays(this))
            {
                var intent = new Intent(Android.Provider.Settings.ActionManageOverlayPermission);
                intent.SetFlags(ActivityFlags.NewTask);
                this.StartActivity(intent);
            }

Thanks in advance!!

**Comment by pytchoun** [comment]
Hey if you can explain the whole code i will be happy :(

**Comment by shernandezp** [comment]
> ```
>         serviceIntent = new Intent(this, typeof(AndroidLocationService));
>         SetServiceMethods();
> 
>         if (Build.VERSION.SdkInt >= BuildVersionCodes.M && !Android.Provider.Settings.CanDrawOverlays(this))
>         {
>             var intent = new Intent(Android.Provider.Settings.ActionManageOverlayPermission);
>             intent.SetFlags(ActivityFlags.NewTask);
>             this.StartActivity(intent);
>         }
> ```
> 
> Thanks in advance!!

https://stackoverflow.com/questions/6391902/how-do-i-start-my-app-on-startup/11863951
